id: I2A7A5312
ocr_import_info:
  timestamp: '2023-10-06T09:40:01.405771+00:00'
  batch_id: batch-9104
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Dharmakyab
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-10-06 13:57:21.108609+00:00
last_modified: 2023-10-06 13:57:21.108616+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W1AC51
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1AC51
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དུས་འཁོར་འགྲེལ་ཆེན་དྲི་མེད་འོད་རྒྱན་དང་དུས་འཁོར་རིམ་གཉིས་ཀྱི་སྨོན་འགྲེལ།
  languages:
  - bo
  author: མཁས་གྲུབ་ནོར་བཟང་རྒྱ་མཚོ།
statistics:
  ocr_word_mean_confidence_index: 0.9949132083523065
  ocr_word_median_confidence_index: 1.0
bases:
  I2PD18532:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD18532
      total_pages: 618
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I2PD18532.txt
    statistics:
      ocr_word_median_confidence_index: 1.0
      ocr_word_mean_confidence_index: 0.9949132083523065
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
